# Generated by Django 5.2.13 on 2026-05-11 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('data_validade', models.DateField()),
                ('fornecedor', models.CharField(default='Secretaria de Saúde', max_length=100)),
                ('quantidade_reservada', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cartao_sus', models.CharField(max_length=15, unique=True, verbose_name='Cartão SUS')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('justificativa_cancelamento', models.TextField(blank=True, null=True)),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='vacinas.estoque')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_estoque', to='vacinas.postosaude'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('item_estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacinas.estoque', verbose_name='Vacina do Estoque')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.paciente')),
                ('posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacinas.postosaude')),
            ],
        ),
    ]
