# Generated by Django 5.2.13 on 2026-05-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0002_offlinesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('ausente', 'Não Compareceu')], default='pendente', max_length=20),
        ),
    ]
