# Generated by Django 5.2.13 on 2026-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0002_postosaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('data_validade', models.DateField()),
                ('fornecedor', models.CharField(default='Secretaria de Saúde', max_length=100)),
            ],
        ),
    ]
