# Generated by Django 5.2.13 on 2026-04-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0003_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postosaude',
            name='vacinas_disponiveis',
        ),
        migrations.AddField(
            model_name='estoque',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_estoque', to='vacinas.postosaude'),
        ),
        migrations.AddField(
            model_name='postosaude',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postosaude',
            name='cep',
            field=models.CharField(default=28240, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postosaude',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
