# Generated by Django 5.2.13 on 2026-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0004_remove_postosaude_vacinas_disponiveis_estoque_posto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='item_estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacinas.estoque', verbose_name='Vacina do Estoque'),
        ),
    ]
