# Generated by Django 5.2.13 on 2026-05-05 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0005_vacina_item_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacinas.postosaude'),
        ),
    ]
