# Generated by Django 5.2.13 on 2026-05-10 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0006_vacina_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('ausente', 'Não Compareceu')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='vacinas.estoque')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.paciente')),
            ],
        ),
    ]
