# Generated by Django 5.2.13 on 2026-05-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0007_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='quantidade_reservada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
