# Generated by Django 5.2.13 on 2026-05-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0008_estoque_quantidade_reservada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
